[package]
name = "gfrh-rs-club-petals-around-the-rose"
version = "0.1.0"
authors = ["Blake"]
edition = "2021"

[dependencies]
anyhow = "1.0"
rand = "0.3.14"
clap = { version = "3", features = ["derive"] }
